#!/usr/bin/env python3
"""
Fair Challenge AI - generate the no-cheat modifier override.

WHY THIS IS A SCRIPT AND NOT A SHIPPED FILE
-------------------------------------------
The AI difficulty bonuses live in common/modifiers/00_static_modifiers.txt.
A mod file with that name REPLACES the vanilla one wholesale - there is no
partial override for this format.

That file also holds weather, resistance, intel, naval and a long tail of
DLC/content-specific modifier blocks, and Paradox adds to it every patch.
So shipping a pre-baked copy would silently delete every block added after
whatever version it was built from, breaking unrelated content.

This script instead reads YOUR installed vanilla file and rewrites only the
AI bonus blocks, so the output always matches your game version exactly.

USAGE
-----
    python3 tools/generate_no_cheat_modifiers.py [--hoi4-dir PATH] [--check]

With no arguments it tries the usual install locations. --check reports what
it would do without writing anything.
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

# Blocks granting the AI something the player does not get.
# diff_normal_ai is deliberately NOT included: its only content is
# no_supply_grace = 36, identical to diff_normal_player, so it is already
# symmetric. Neutralising it would make the AI strictly worse than the
# player, which is just cheating in the other direction.
AI_BONUS_BLOCKS = [
    "diff_very_easy_ai",
    "diff_easy_ai",
    "diff_hard_ai",
    "diff_very_hard_ai",
    "diff_strong_ai_generic",
]

REL_PATH = Path("common") / "modifiers" / "00_static_modifiers.txt"

DEFAULT_HOI4_DIRS = [
    Path.home() / ".steam/steam/steamapps/common/Hearts of Iron IV",
    Path.home() / ".local/share/Steam/steamapps/common/Hearts of Iron IV",
    Path("/Applications/Hearts of Iron IV.app/Contents/Resources"),
    Path.home() / "Library/Application Support/Steam/steamapps/common/Hearts of Iron IV",
    Path("C:/Program Files (x86)/Steam/steamapps/common/Hearts of Iron IV"),
    Path("D:/Steam/steamapps/common/Hearts of Iron IV"),
]

BANNER = (
    "# ===================================================================\n"
    "# Generated by Fair Challenge AI - tools/generate_no_cheat_modifiers.py\n"
    "#\n"
    "# This is your game's own 00_static_modifiers.txt with the AI bonus\n"
    "# blocks emptied. Every other block is byte-identical to vanilla.\n"
    "#\n"
    "# Neutralised: " + ", ".join(AI_BONUS_BLOCKS) + "\n"
    "#\n"
    "# Regenerate this file after any game update.\n"
    "# ===================================================================\n\n"
)


def find_vanilla(explicit: Path | None) -> Path:
    """Locate the vanilla 00_static_modifiers.txt."""
    candidates = [explicit] if explicit else DEFAULT_HOI4_DIRS
    for base in candidates:
        if base is None:
            continue
        target = base / REL_PATH
        if target.is_file():
            return target
    searched = "\n  ".join(str(c / REL_PATH) for c in candidates if c)
    raise SystemExit(
        "Could not find vanilla 00_static_modifiers.txt.\n"
        f"Looked in:\n  {searched}\n\n"
        "Pass your install directory explicitly:\n"
        '  python3 tools/generate_no_cheat_modifiers.py --hoi4-dir "/path/to/Hearts of Iron IV"'
    )


def find_block(text: str, name: str) -> tuple[int, int] | None:
    """Return (start, end) char offsets of a top-level `name = { ... }` block.

    Brace-counted rather than regexed, because these blocks contain nested
    braces and comments.
    """
    match = re.search(rf"^{re.escape(name)}\s*=\s*{{", text, re.MULTILINE)
    if not match:
        return None

    depth = 0
    for i in range(match.start(), len(text)):
        char = text[i]
        if char == "#":  # skip to end of comment line
            newline = text.find("\n", i)
            if newline == -1:
                break
            continue
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return match.start(), i + 1
    return None


def neutralise(text: str) -> tuple[str, list[str], list[str]]:
    """Empty each AI bonus block. Returns (new_text, changed, missing)."""
    changed: list[str] = []
    missing: list[str] = []

    # Work back-to-front so earlier offsets stay valid as we splice.
    spans = []
    for name in AI_BONUS_BLOCKS:
        span = find_block(text, name)
        if span is None:
            missing.append(name)
        else:
            spans.append((span, name))

    for (start, end), name in sorted(spans, reverse=True):
        replacement = (
            f"{name} = {{\n"
            f"\t# Emptied by Fair Challenge AI: the AI plays by the player's rules.\n"
            f"}}"
        )
        if text[start:end] != replacement:
            text = text[:start] + replacement + text[end:]
            changed.append(name)

    return text, changed, missing


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--hoi4-dir", type=Path, default=None, help="HOI4 installation directory")
    parser.add_argument("--check", action="store_true", help="report only, write nothing")
    args = parser.parse_args()

    vanilla_path = find_vanilla(args.hoi4_dir)
    print(f"vanilla source : {vanilla_path}")

    original = vanilla_path.read_text(encoding="utf-8-sig", errors="replace")
    patched, changed, missing = neutralise(original)

    for name in changed:
        print(f"  neutralised  : {name}")
    for name in missing:
        print(f"  NOT FOUND    : {name} (renamed or removed in this version - review manually)")

    if not changed:
        print("\nNothing to change. Either it is already generated, or the block "
              "names moved in this game version - check the file manually.")
        return 1

    out_path = Path(__file__).resolve().parent.parent / REL_PATH
    if args.check:
        print(f"\n--check: would write {out_path} ({len(patched):,} bytes)")
        return 0

    out_path.parent.mkdir(parents=True, exist_ok=True)
    if out_path.exists():
        backup = out_path.with_suffix(".txt.bak")
        shutil.copy2(out_path, backup)
        print(f"  backed up    : {backup.name}")

    out_path.write_text(BANNER + patched, encoding="utf-8")
    print(f"\nwrote {out_path} ({len(patched):,} bytes, {len(changed)} block(s) neutralised)")
    print("Re-run this after every HOI4 update.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
